language: node_js
node_js:
  - "8"

env:
  global:
    - TRAVIS=true
    - SAUCE_USERNAME="stopsopa-test"
    - secure: eeFmoUxofQPSC6RoOQy362GAV91dmRN0tyri5+JSoYIQYfyc1c961Pzn+m1JooZ3lcEDIUWGjIvmj7q8TnZFjj80YSZIKSmd4xdC0KmPzuH/7G8dzvuIfksIlzjR8mIpWMtonl7CsjihTsflaku1wAVQFRNouAT8McIIqO3dbIyeQllNnbq47Z3HQXsgcRUGSh12VlYPsJoG2ikCT4FY4fXMOI0gi3/oLLOLsyiSTnTMPOuRg1uMxoB7FaAxFm06ZOtBwKBh20iaSIpgyEfFKH2OdnvLzBQ4QS1j0/55e03jXPnnu6ARcL2VvbYYx1ThXOgSW/Q2D0mQkz21snPK3hJdYopUnkvBaedLbGWXy9gTu3tVAco01H3l1y/AJJdEpOaWRA7abg2I086jVBL+I5+YvqOHzRrpEgkNbvNOWvtKookY0eZg3C10Xe8i2EKkO+sBCKQdgQTL7tFkG/Ns0kNkLzEfrk6QD5ajO/pX7XX0QjpfVvW/LKniSSQz5Tbf0PV3WPuKmlm2F6x76qjEpFjXgGJ1vCSzja8RR2QpDEO13bmC57hT/iS5mIIcAjYROGxyCliOmbkuUYrj/GPrAmmuXQrJqRDFBPfxr5V9FVnA0QhhVEqwsixMKnH/fR56E9P8AHF13gtG1Uu1JTuIlnCgW0gba7jL6wk5WhCMmik=
    - secure: BzPg6hWeRSXwt4exmKvXUvwr8eIMWb+SJhM/nV3EsOmw7lwyodSY5PLwRcbcE1uMNkNpl11trNztC1ZtIaGenJTHM8+/BkqgxsFGpcIvqinX3U3xUJvlyA8rUPBeb1bAh4S1A33JtyPt9yyCraZD38x4yFJXukTLkQ+9ChdE1E4P2aQGfJ6ch80cGGzrnZI14AcZNvgn0TOUtJlhbSShaQfTgH8qIfM/6OgqVyldDfo9WJK/jbGT6wKGGndHHFBgCNGXSZ90WabTyr7YgjSRigrr2zUFpP0r+mY4eEhNx5F0WXpvIGCF2wO6Yn/OtFc6DsyQRbNkeaZyzfjb+MjZygAbkyHQQG+HUFp3/44svQX/ahI2zXKh09bGC3CAN/9ug7Q0MMhyXPZbq/PKO17fu1L4Qh+PTy6Jm8Sz1fzGXor2KVch9UlD7OFiGLrYNPzpNVxIamoQmi1UgMM/OiSNFUpHotS81mdg6Y0oXtECOU7oNlR5Fr8OnyrUOpKUlBVJ9b3JCMANNe3QHVKT48eur88RuGtBA3kiH4ElFv0ldAlkWCrvGe0x6KBdr/LKwJNHJ7k18ORz4mHSoaxoPjZ0Szr4Iu1cViGs+BShZOKuI1W8aFBNtUXwhUz0S7AnRi7lroS2lRXq59hPT43RvIeDuhd79Qs/IAJmn3xVn+/Cxyw=

before_script:
#  - make test-server & disown
#  - sleep 2
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod a+x chromedriver

script:
#  - node node_modules/.bin/jest --verbose --runInBand --verbose test/examples/006

  - printenv
  - foo=TEST_VAR
  - eval echo \${$foo} > test.log
  - cat test.log

#addons:
#  sauce_connect:
#    username: "stopsopa-test"
#  jwt:
#    secure: "L39kinFOFke3MjOlFPN0sUM1KyTS0B2xb0Q6UdUY4gMt6XkNarfpNtwyzMnnsWHPRClQQILeDQzBt8hTeq4QIIbxW2bkFkiQo+XL+Bve5XUsmzlRDSp5BYO8UMmyCUdAmFjct3UX7WSf3yY1uKWGxXpO0MJqjmjfEwzhILMwzu2UfNxo4Vw59hDcLhXq+x5EASWDcKQPi/Uej+GkoNWYYsQk0u2qB6e1dx/2xy5yIXTKFB5QwjzzuisR8ljS8tr47+y2kKEAIJG+cCvzVqUBkjv4QxN/eZ2AGAo49FeuhSTY0EgCN40t8OsihCHllkVdKd9s6czUAYEsWRTO5bcrE6nto0l/nzyps25+92omxtRjwqI5ghoMbsNgKUnx1WgdMGPzCacNGmeCUjWzv244cC00Zt7aFJ+oRE3nCpYO1A6SivS3KsIwCzYepSHCgzClCUlC/jjClYuu7j/L1q91D+phdp5/36TZIPN2u5QowN0B2GnqIKvSJXImNMv0wi5yWV2rJIlI8lY7v6mZdmUUU5JRNaFdZbwzLLB+DCxaMOHX+Lcsdvlq2Fut7XOcrXFE9plyPp04S/NhLvm3xlI7BghXjriJH4j9pFC1igVuCksdhT1aSuXm8emvXktowi/F91IcXBENQwgHk119YcSWIeewT4nwekbGmpKmtkmwJlI="